export interface IDocLocWiseInvestment {
    id: number;
    sbuName: string;
    sbuCode: string;
    marketCode: string;
    marketName: string;
    territoryCode: string;
    territoryName: string;
    regionCode: string;
    regionName: string;
    divisionCode: string;
    divisionName: string;
    zoneCode: string;
    zoneName: string;
    doctorId: string;
    doctorName: string;
    institutionId: string;
    institutionName: string;
    donationType: string;
    fromDate: Date | undefined | null;
    toDate: Date | undefined | null;
    investedAmt: number;
    commitment: string;
    actualShare: string;
    competitorShare: string;
    noOfPresc: string;
    noOfPatient: string;
    deviation: string;
    leaderNonLeader: string;
}